### ISSUE TITLE
關於 Uchiage Hanabi 字幕的問題

### ISSUE THREAD

**Issue by husk0808** [Nekomoekissaten-SUB/Nekomoekissaten-poi-Subs#3]
我看到貴組選擇的字體edjp 使用Source Han Serif JP Medium 大小105
這大小非常之大 在較新的播放器 或 字幕繪製下 會正常繪製 倒置字體明顯超級大
在使用舊版問題較多的內部繪製 下 由於舊本可能是BUG比較多 到至他播放起來較小 
edcn 也才28 
28跟105明顯就能看出105非常有問題!
若當初設計是要大小一樣 是否考慮發布版本字體大小改回28

**Comment by MIRIMIRIM** [comment]
用 *VSFilter* 系字幕渲染器時，同字號下直式的 *Source Han* 系列字體明顯會比橫式的要小很多，*libass* 則沒有這個問題。顯示過大可能是因爲你使用了 *libass* 做字幕渲染，其他的字體也可能會有些微的差異，有興趣的話可以看下 [這個 issue](https://github.com/libass/libass/issues/619)。

我可能會考慮更換字體來規避這個問題，晚些時間會對此進行修復。
